org.gradle.jvmargs=-Xmx6g -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.vfs.watch=true
android.nonTransitiveRClass=true
kotlin.code.style=official
org.gradle.workers.max=8
kotlin.compiler.execution.strategy=daemon
ksp.incremental=true
kotlin.incremental=true
android.builtInKotlin=false
android.newDsl=false
