package com.notimind.lite.tier1_feature

import com.jeffers.notimindlite.data.local.NotificationEntity
import com.notimind.lite.base.BaseRobolectricTest
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.runTest
import org.junit.Assert.*
import org.junit.Test

class PersistenceSchemaTest : BaseRobolectricTest() {

    @Test
    fun tc_R2_T1_001_roomEntityFieldsAndDefaultValuesIntegrity() {
        val entity = NotificationEntity(
            key = "pkg.app_101",
            packageName = "com.test.app",
            appName = "Test App",
            title = "Hello",
            content = "World"
        )

        assertEquals("Default id must be 0", 0L, entity.id)
        assertTrue("postTime default should be positive epoch", entity.postTime > 0L)
        assertFalse("isDismissed default must be false", entity.isDismissed)
        assertFalse("isPersistent default must be false", entity.isPersistent)
        assertEquals("pkg.app_101", entity.key)
        assertEquals("com.test.app", entity.packageName)
        assertEquals("Test App", entity.appName)
        assertEquals("Hello", entity.title)
        assertEquals("World", entity.content)
    }

    @Test
    fun tc_R2_T1_002_notificationDaoInsertOperationAndAutoGeneratedKeys() = runTest {
        val e1 = createDummyEntity(key = "k1")
        val e2 = createDummyEntity(key = "k2")

        val id1 = dao.insertNotification(e1)
        val id2 = dao.insertNotification(e2)

        assertTrue("First inserted row ID should be > 0", id1 > 0)
        assertTrue("Second inserted row ID should be > first", id2 > id1)
        assertEquals("Total notification count must be 2", 2, dao.getNotificationCount())
    }

    @Test
    fun tc_R2_T1_003_notificationDaoQueryActiveNotificationsFlowAndList() = runTest {
        val now = System.currentTimeMillis()
        val e1 = createDummyEntity(key = "k1", postTime = now - 2000, isDismissed = false)
        val e2 = createDummyEntity(key = "k2", postTime = now - 1000, isDismissed = true)
        val e3 = createDummyEntity(key = "k3", postTime = now, isDismissed = false)

        dao.insertNotification(e1)
        dao.insertNotification(e2)
        dao.insertNotification(e3)

        val activeList = dao.getActiveNotificationsList()
        val activeFlowList = dao.getActiveNotificationsFlow().first()

        assertEquals("Active list size must be 2", 2, activeList.size)
        assertEquals("Active flow list size must be 2", 2, activeFlowList.size)

        assertEquals("k3", activeList[0].key)
        assertEquals("k1", activeList[1].key)
    }

    @Test
    fun tc_R2_T1_004_notificationDaoQueryAllNotificationsHistoryLog() = runTest {
        val now = System.currentTimeMillis()
        val e1 = createDummyEntity(key = "k1", postTime = now - 1000, isDismissed = false)
        val e2 = createDummyEntity(key = "k2", postTime = now, isDismissed = true)

        dao.insertNotification(e1)
        dao.insertNotification(e2)

        val allLogs = dao.getAllNotifications().first()
        assertEquals("All notifications size must be 2", 2, allLogs.size)
        assertEquals("k2", allLogs[0].key)
        assertEquals("k1", allLogs[1].key)
    }

    @Test
    fun tc_R2_T1_005_notificationDaoMarkDismissedStateUpdate() = runTest {
        val entity = createDummyEntity(key = "key_to_dismiss", isDismissed = false)
        dao.insertNotification(entity)

        assertEquals(1, dao.getActiveNotificationsList().size)

        dao.markDismissed("key_to_dismiss")

        assertEquals(0, dao.getActiveNotificationsList().size)

        val allLogs = dao.getAllNotifications().first()
        assertEquals(1, allLogs.size)
        assertTrue("isDismissed must be true", allLogs[0].isDismissed)
    }

    @Test
    fun tc_R2_T1_006_notificationDaoClearAllWipingDatabaseTable() = runTest {
        for (i in 1..5) {
            dao.insertNotification(createDummyEntity(key = "k_$i", isDismissed = i % 2 == 0))
        }

        assertEquals(5, dao.getNotificationCount())

        // Clear all DB rows
        dao.clearAll()

        assertEquals(0, dao.getNotificationCount())
        assertTrue("getAllNotifications must be empty", dao.getAllNotifications().first().isEmpty())
    }
}
